### ISSUE TITLE
no package.json

### ISSUE THREAD

**Issue by goofballLogic** [FallenMan13/Data-summarization#5]
There is no package.json in this repository. This means that when I run ```node JmeterDataSummary``` it gives me an error:
```
~/src/Data-summarization$ node JmeterDataSummary
module.js:471
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/andrew/src/Data-summarization/getPage.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3
```

**Comment by FallenMan13** [comment]
package.json file created and added to master branch

**Comment by goofballLogic** [comment]
OK, now I can run it, but when I accept the defaults, it just says "Indexing complete". What should it do?

**Comment by FallenMan13** [comment]
For the moment the default date range will produce no data since the jmeter tests weren't indexing data from midnight to an hour later. If you enter the date range of 2017-03-08T09:00:00.000Z to 2017-03-08T10:00:00.000Z there should be a different response upon attempting to index the data. I'll add some code to the index operation to make it more descriptive.

**Comment by FallenMan13** [comment]
Index operation should now log the response to the console if there was a 4xx error

**Comment by goofballLogic** [comment]
ok, seems good now
